import type { HubDef } from '../types';

export const cnBroadHub: HubDef = {
  market: 'cn',
  module: 'broad',
  slug: '/cn/broad',
  lang: 'zh-CN',
  title: '宽基与时代 | A股编年史',
  description: '以核心宽基指数为锚，观察长期回报形状、年度波动、回撤与估值钟摆。',
  heroTitle: 'The Market / 宽基',
  heroDescription: '把一条指数拉到足够长，答案会从“涨跌”变成“形状”：回报、回撤、估值与结构一起决定这段复利曲线。',
  sections: [
    {
      sectionNumber: '1',
      title: '核心指数',
      panelKeys: ['shanghai-composite', 'shenzhen-component', 'hs300', 'chinext', 'star50', 'csi500', 'csi1000', 'csi-dividend'],
    },
    {
      sectionNumber: '1.1',
      title: '沪深300（核心图）',
      panelKeys: ['hs300', 'hs300tr', 'hs300annual', 'hs300dd', 'hs300val', 'hs300eps'],
    },
    {
      sectionNumber: '1.2',
      title: '上证综指（核心图）',
      panelKeys: ['shanghai-composite', 'shcomptr', 'shcompannual', 'shcompdd'],
    },
    {
      sectionNumber: '1.3',
      title: '中证500（核心图）',
      panelKeys: ['csi500', 'csi500tr', 'csi500annual', 'csi500dd'],
    },
    {
      sectionNumber: '1.4',
      title: '科创50（核心图）',
      panelKeys: ['star50', 'star50tr', 'star50annual', 'star50dd'],
    },
    {
      sectionNumber: '1.7',
      title: '中证1000（核心图）',
      panelKeys: ['csi1000', 'csi1000tr', 'csi1000annual', 'csi1000dd'],
    },
    {
      sectionNumber: '1.8',
      title: '中证红利（核心图）',
      panelKeys: ['csi-dividend', 'csidivtr', 'csidivannual', 'csidivdd'],
    },
    {
      sectionNumber: '1.5',
      title: '深证成指（核心图）',
      panelKeys: ['shenzhen-component', 'szcomptr', 'szcompannual', 'szcompdd'],
    },
    {
      sectionNumber: '1.6',
      title: '创业板指（核心图）',
      panelKeys: ['chinext', 'chinexttr', 'chinextannual', 'chinextdd'],
    },
    {
      sectionNumber: '2',
      title: '周期与风险',
      panelKeys: ['annual', 'drawdown', 'intrayear-turbulence', 'volatility'],
    },
    {
      sectionNumber: '3',
      title: '估值与拆解',
      panelKeys: ['valuation', 'davis-decomposition', 'distribution', 'style-ratios', 'seasonality'],
    },
    {
      sectionNumber: '4',
      title: '结构与效率',
      panelKeys: ['sector-evolution', 'roe-anchor', 'breadth', 'concentration', 'eras'],
    },
  ],
  panels: {
    'shanghai-composite': {
      key: 'shanghai-composite',
      title: '上证综指（000001）',
      description: '最“老”的那条曲线：从 1990 年起的市场总览。',
      lead: '上证综指并不“代表中国最好公司”，但它记录了资本市场从无到有的全部噪声与全部周期。',
      apiPath: '/api/cn/broad/shanghai-composite.json',
      chart: { id: 'cn-broad-shanghai-composite', title: '上证综指长期价格' },
      howToRead: '把它当作“市场体温计”而不是投资组合：关注长期区间的回撤深度与修复耗时，而非单点高低。',
      sources: ['数据：中证指数公司（CSIndex）指数行情 index-perf（000001）。'],
      relatedKeys: ['shcompdd', 'shcompannual', 'eras'],
    },
    shcomptr: {
      key: 'shcomptr',
      title: '上证综指总回报',
      description: '含分红再投入的全收益指数。',
      apiPath: '/api/cn/broad/shanghai-composite-total-return.json',
      chart: { id: 'cn-broad-shcomp-tr', title: '上证综指总回报指数（000888）' },
      sources: ['数据：中证指数公司（CSIndex）指数行情 index-perf（000888）。'],
      relatedKeys: ['shanghai-composite', 'shcompdd', 'shcompannual'],
    },
    shcompannual: {
      key: 'shcompannual',
      title: '上证综指年度回报',
      description: '用全收益指数结账每一年的回报。',
      apiPath: '/api/cn/broad/shanghai-composite-annual-returns.json',
      chart: { id: 'cn-broad-shcomp-annual', title: '上证综指年度回报（总回报）' },
      sources: ['数据：CSIndex（000888）；计算：以每年最后一个交易日收盘价计算年度回报。'],
      relatedKeys: ['shcomptr', 'shcompdd'],
    },
    shcompdd: {
      key: 'shcompdd',
      title: '上证综指回撤名册',
      description: '深度/持续/修复：把回撤变成可检索的事件。',
      apiPath: '/api/cn/broad/shanghai-composite-drawdowns.json',
      chart: { id: 'cn-broad-shcomp-dd', title: '上证综指历史回撤（总回报）' },
      sources: ['数据：CSIndex（000888）；计算：相对历史峰值的回撤（%），并按“开始-最低-修复”生成事件目录。'],
      relatedKeys: ['shcomptr', 'shcompannual'],
    },
    'shenzhen-component': {
      key: 'shenzhen-component',
      title: '深证成指（399001）',
      description: '更偏成长与中小盘的一面镜子。',
      apiPath: '/api/cn/broad/shenzhen-component.json',
      chart: { id: 'cn-broad-shenzhen-component', title: '深证成指长期价格' },
      sources: ['数据：搜狐证券历史行情（zs_399001）。'],
      relatedKeys: ['szcompdd', 'szcompannual', 'chinext'],
    },
    szcomptr: {
      key: 'szcomptr',
      title: '深证成指总回报（代理）',
      description: '暂以价格指数近似总回报。',
      apiPath: '/api/cn/broad/shenzhen-component-total-return.json',
      chart: { id: 'cn-broad-szcomp-tr', title: '深证成指总回报（代理）' },
      sources: ['数据：搜狐证券（zs_399001）；暂以价格指数近似总回报（不含分红再投入）。'],
      relatedKeys: ['shenzhen-component', 'szcompdd', 'szcompannual'],
    },
    szcompannual: {
      key: 'szcompannual',
      title: '深证成指年度回报',
      description: '用价格指数结账每一年的回报（暂）。',
      apiPath: '/api/cn/broad/shenzhen-component-annual-returns.json',
      chart: { id: 'cn-broad-szcomp-annual', title: '深证成指年度回报（暂）' },
      sources: ['数据：搜狐证券（zs_399001）；计算：以每年最后一个交易日收盘价计算年度回报（暂基于价格指数）。'],
      relatedKeys: ['szcomptr', 'szcompdd'],
    },
    szcompdd: {
      key: 'szcompdd',
      title: '深证成指回撤名册',
      description: '深度/持续/修复：把回撤变成可检索的事件（暂）。',
      apiPath: '/api/cn/broad/shenzhen-component-drawdowns.json',
      chart: { id: 'cn-broad-szcomp-dd', title: '深证成指历史回撤（暂）' },
      sources: ['数据：搜狐证券（zs_399001）；计算：相对历史峰值的回撤（%），并按“开始-最低-修复”生成事件目录（暂基于价格指数）。'],
      relatedKeys: ['szcomptr', 'szcompannual'],
    },
    hs300: {
      key: 'hs300',
      title: '沪深300（000300）',
      description: '机构化时代的核心资产篮子。',
      apiPath: '/api/cn/broad/hs300.json',
      chart: { id: 'cn-broad-hs300', title: '沪深300长期价格' },
      sources: ['数据：中证指数公司（CSIndex）指数行情 index-perf（000300）。'],
      relatedKeys: ['valuation', 'sector-evolution', 'roe-anchor'],
    },
    hs300tr: {
      key: 'hs300tr',
      title: '沪深300总回报',
      description: '含分红再投入的全收益指数。',
      apiPath: '/api/cn/broad/hs300-total-return.json',
      chart: { id: 'cn-broad-hs300-tr', title: '沪深300总回报指数（H00300）' },
      sources: ['数据：中证指数公司（CSIndex）指数行情 index-perf（H00300）。'],
      relatedKeys: ['hs300', 'hs300dd', 'hs300annual'],
    },
    hs300annual: {
      key: 'hs300annual',
      title: '沪深300年度回报',
      description: '用全收益指数结账每一年的回报。',
      apiPath: '/api/cn/broad/hs300-annual-returns.json',
      chart: { id: 'cn-broad-hs300-annual', title: '沪深300年度回报（总回报）' },
      sources: ['数据：CSIndex（H00300）；计算：以每年最后一个交易日收盘价计算年度回报。'],
      relatedKeys: ['hs300tr', 'hs300dd'],
    },
    hs300dd: {
      key: 'hs300dd',
      title: '沪深300回撤名册',
      description: '深度/持续/修复：把回撤变成可检索的事件。',
      apiPath: '/api/cn/broad/hs300-drawdowns.json',
      chart: { id: 'cn-broad-hs300-dd', title: '沪深300历史回撤（总回报）' },
      sources: ['数据：CSIndex（H00300）；计算：相对历史峰值的回撤（%），并按“开始-最低-修复”生成事件目录。'],
      relatedKeys: ['hs300tr', 'hs300annual'],
    },
    hs300val: {
      key: 'hs300val',
      title: '沪深300估值',
      description: 'PE 走势与标准差通道。',
      apiPath: '/api/cn/broad/hs300-valuation.json',
      chart: { id: 'cn-broad-hs300-val', title: '沪深300估值（PE1）' },
      sources: ['数据：中证指数公司（CSIndex）指数估值文件（indicator/000300indicator.xls）。'],
      relatedKeys: ['hs300eps', 'hs300'],
    },
    hs300eps: {
      key: 'hs300eps',
      title: '沪深300盈利（EPS）',
      description: '用 PE 与点位反推出“盈利曲线”的形状。',
      apiPath: '/api/cn/broad/hs300-eps.json',
      chart: { id: 'cn-broad-hs300-eps', title: '沪深300盈利（推算）' },
      sources: ['计算：EPS≈指数点位/PE1；PE1 来自 CSIndex 指数估值文件。'],
      relatedKeys: ['hs300val', 'hs300tr'],
    },
    chinext: {
      key: 'chinext',
      title: '创业板指（399006）',
      description: '成长股的高波动样本。',
      apiPath: '/api/cn/broad/chinext.json',
      chart: { id: 'cn-broad-chinext', title: '创业板指长期价格' },
      sources: ['数据：搜狐证券历史行情（zs_399006）。'],
      relatedKeys: ['chinextdd', 'chinextannual', 'distribution'],
    },
    chinexttr: {
      key: 'chinexttr',
      title: '创业板指总回报（代理）',
      description: '暂以价格指数近似总回报。',
      apiPath: '/api/cn/broad/chinext-total-return.json',
      chart: { id: 'cn-broad-chinext-tr', title: '创业板指总回报（代理）' },
      sources: ['数据：搜狐证券（zs_399006）；暂以价格指数近似总回报（不含分红再投入）。'],
      relatedKeys: ['chinext', 'chinextdd', 'chinextannual'],
    },
    chinextannual: {
      key: 'chinextannual',
      title: '创业板指年度回报',
      description: '用价格指数结账每一年的回报（暂）。',
      apiPath: '/api/cn/broad/chinext-annual-returns.json',
      chart: { id: 'cn-broad-chinext-annual', title: '创业板指年度回报（暂）' },
      sources: ['数据：搜狐证券（zs_399006）；计算：以每年最后一个交易日收盘价计算年度回报（暂基于价格指数）。'],
      relatedKeys: ['chinexttr', 'chinextdd'],
    },
    chinextdd: {
      key: 'chinextdd',
      title: '创业板指回撤名册',
      description: '深度/持续/修复：把回撤变成可检索的事件（暂）。',
      apiPath: '/api/cn/broad/chinext-drawdowns.json',
      chart: { id: 'cn-broad-chinext-dd', title: '创业板指历史回撤（暂）' },
      sources: ['数据：搜狐证券（zs_399006）；计算：相对历史峰值的回撤（%），并按“开始-最低-修复”生成事件目录（暂基于价格指数）。'],
      relatedKeys: ['chinexttr', 'chinextannual'],
    },
    star50: {
      key: 'star50',
      title: '科创50（000688）',
      description: '硬科技定价与风险偏好变化的窗口。',
      apiPath: '/api/cn/broad/star50.json',
      chart: { id: 'cn-broad-star50', title: '科创50长期价格' },
      sources: ['数据：中证指数公司（CSIndex）指数行情 index-perf（000688）。'],
      relatedKeys: ['star50dd', 'star50annual', 'valuation'],
    },
    star50tr: {
      key: 'star50tr',
      title: '科创50总回报',
      description: '含分红再投入的全收益指数。',
      apiPath: '/api/cn/broad/star50-total-return.json',
      chart: { id: 'cn-broad-star50-tr', title: '科创50总回报指数（000688CNY01）' },
      sources: ['数据：中证指数公司（CSIndex）指数行情 index-perf（000688CNY01）。'],
      relatedKeys: ['star50', 'star50dd', 'star50annual'],
    },
    star50annual: {
      key: 'star50annual',
      title: '科创50年度回报',
      description: '用全收益指数结账每一年的回报。',
      apiPath: '/api/cn/broad/star50-annual-returns.json',
      chart: { id: 'cn-broad-star50-annual', title: '科创50年度回报（总回报）' },
      sources: ['数据：CSIndex（000688CNY01）；计算：以每年最后一个交易日收盘价计算年度回报。'],
      relatedKeys: ['star50tr', 'star50dd'],
    },
    star50dd: {
      key: 'star50dd',
      title: '科创50回撤名册',
      description: '深度/持续/修复：把回撤变成可检索的事件。',
      apiPath: '/api/cn/broad/star50-drawdowns.json',
      chart: { id: 'cn-broad-star50-dd', title: '科创50历史回撤（总回报）' },
      sources: ['数据：CSIndex（000688CNY01）；计算：相对历史峰值的回撤（%），并按“开始-最低-修复”生成事件目录。'],
      relatedKeys: ['star50tr', 'star50annual'],
    },
    csi500: {
      key: 'csi500',
      title: '中证500（000905）',
      description: '中盘弹性的代表。',
      apiPath: '/api/cn/broad/csi500.json',
      chart: { id: 'cn-broad-csi500', title: '中证500长期价格' },
      sources: ['数据：中证指数公司（CSIndex）指数行情 index-perf（000905）。'],
      relatedKeys: ['csi500dd', 'csi500annual', 'style-ratios'],
    },
    csi500tr: {
      key: 'csi500tr',
      title: '中证500总回报',
      description: '含分红再投入的全收益指数。',
      apiPath: '/api/cn/broad/csi500-total-return.json',
      chart: { id: 'cn-broad-csi500-tr', title: '中证500总回报指数（H00905）' },
      sources: ['数据：中证指数公司（CSIndex）指数行情 index-perf（H00905）。'],
      relatedKeys: ['csi500', 'csi500dd', 'csi500annual'],
    },
    csi500annual: {
      key: 'csi500annual',
      title: '中证500年度回报',
      description: '用全收益指数结账每一年的回报。',
      apiPath: '/api/cn/broad/csi500-annual-returns.json',
      chart: { id: 'cn-broad-csi500-annual', title: '中证500年度回报（总回报）' },
      sources: ['数据：CSIndex（H00905）；计算：以每年最后一个交易日收盘价计算年度回报。'],
      relatedKeys: ['csi500tr', 'csi500dd'],
    },
    csi500dd: {
      key: 'csi500dd',
      title: '中证500回撤名册',
      description: '深度/持续/修复：把回撤变成可检索的事件。',
      apiPath: '/api/cn/broad/csi500-drawdowns.json',
      chart: { id: 'cn-broad-csi500-dd', title: '中证500历史回撤（总回报）' },
      sources: ['数据：CSIndex（H00905）；计算：相对历史峰值的回撤（%），并按“开始-最低-修复”生成事件目录。'],
      relatedKeys: ['csi500tr', 'csi500annual'],
    },
    csi1000: {
      key: 'csi1000',
      title: '中证1000（000852）',
      description: '小盘宽基：更接近“中小市值的β”。',
      apiPath: '/api/cn/broad/csi1000.json',
      chart: { id: 'cn-broad-csi1000', title: '中证1000长期价格' },
      sources: ['数据：中证指数公司（CSIndex）指数行情 index-perf（000852）。'],
      relatedKeys: ['csi1000dd', 'csi1000annual', 'style-ratios'],
    },
    csi1000tr: {
      key: 'csi1000tr',
      title: '中证1000总回报',
      description: '含分红再投入的全收益指数。',
      apiPath: '/api/cn/broad/csi1000-total-return.json',
      chart: { id: 'cn-broad-csi1000-tr', title: '中证1000总回报指数（H00852）' },
      sources: ['数据：中证指数公司（CSIndex）指数行情 index-perf（H00852）。'],
      relatedKeys: ['csi1000', 'csi1000dd', 'csi1000annual'],
    },
    csi1000annual: {
      key: 'csi1000annual',
      title: '中证1000年度回报',
      description: '用全收益指数结账每一年的回报。',
      apiPath: '/api/cn/broad/csi1000-annual-returns.json',
      chart: { id: 'cn-broad-csi1000-annual', title: '中证1000年度回报（总回报）' },
      sources: ['数据：CSIndex（H00852）；计算：以每年最后一个交易日收盘价计算年度回报。'],
      relatedKeys: ['csi1000tr', 'csi1000dd'],
    },
    csi1000dd: {
      key: 'csi1000dd',
      title: '中证1000回撤名册',
      description: '深度/持续/修复：把回撤变成可检索的事件。',
      apiPath: '/api/cn/broad/csi1000-drawdowns.json',
      chart: { id: 'cn-broad-csi1000-dd', title: '中证1000历史回撤（总回报）' },
      sources: ['数据：CSIndex（H00852）；计算：相对历史峰值的回撤（%），并按“开始-最低-修复”生成事件目录。'],
      relatedKeys: ['csi1000tr', 'csi1000annual'],
    },
    'csi-dividend': {
      key: 'csi-dividend',
      title: '中证红利（000922）',
      description: '红利因子：把现金流暴露显性化。',
      apiPath: '/api/cn/broad/csi-dividend.json',
      chart: { id: 'cn-broad-csidiv', title: '中证红利长期价格' },
      sources: ['数据：中证指数公司（CSIndex）指数行情 index-perf（000922）。'],
      relatedKeys: ['csidivdd', 'csidivannual', 'valuation'],
    },
    csidivtr: {
      key: 'csidivtr',
      title: '中证红利总回报',
      description: '含分红再投入的全收益指数。',
      apiPath: '/api/cn/broad/csi-dividend-total-return.json',
      chart: { id: 'cn-broad-csidiv-tr', title: '中证红利总回报指数（H00922）' },
      sources: ['数据：中证指数公司（CSIndex）指数行情 index-perf（H00922）。'],
      relatedKeys: ['csi-dividend', 'csidivdd', 'csidivannual'],
    },
    csidivannual: {
      key: 'csidivannual',
      title: '中证红利年度回报',
      description: '用全收益指数结账每一年的回报。',
      apiPath: '/api/cn/broad/csi-dividend-annual-returns.json',
      chart: { id: 'cn-broad-csidiv-annual', title: '中证红利年度回报（总回报）' },
      sources: ['数据：CSIndex（H00922）；计算：以每年最后一个交易日收盘价计算年度回报。'],
      relatedKeys: ['csidivtr', 'csidivdd'],
    },
    csidivdd: {
      key: 'csidivdd',
      title: '中证红利回撤名册',
      description: '深度/持续/修复：把回撤变成可检索的事件。',
      apiPath: '/api/cn/broad/csi-dividend-drawdowns.json',
      chart: { id: 'cn-broad-csidiv-dd', title: '中证红利历史回撤（总回报）' },
      sources: ['数据：CSIndex（H00922）；计算：相对历史峰值的回撤（%），并按“开始-最低-修复”生成事件目录。'],
      relatedKeys: ['csidivtr', 'csidivannual'],
    },
    annual: {
      key: 'annual',
      title: '年度回报',
      description: '把“长期复利”拆回每一年的结账。',
      apiPath: '/api/cn/broad/annual.json',
      chart: { id: 'cn-broad-annual', title: '年度回报（示例）' },
      howToRead: '正负柱体之外，更重要的是：盈利年/亏损年的频率、极端年份的肥尾，以及它们如何塑造风险承受能力。',
      relatedKeys: ['distribution', 'drawdown'],
    },
    drawdown: {
      key: 'drawdown',
      title: '回撤名册',
      description: '市场给恐惧开出的价格：深度与修复。',
      apiPath: '/api/cn/broad/drawdown.json',
      chart: { id: 'cn-broad-drawdown', title: '历史回撤（示例）' },
      relatedKeys: ['annual', 'intrayear-turbulence'],
    },
    'intrayear-turbulence': {
      key: 'intrayear-turbulence',
      title: '年内波动',
      description: '同一年里，最大回撤与最终收益的反差。',
      apiPath: '/api/cn/broad/intrayear-turbulence.json',
      chart: { id: 'cn-broad-intrayear', title: '年内最大回撤 vs 年终收益（示例）' },
      relatedKeys: ['drawdown', 'annual'],
    },
    volatility: {
      key: 'volatility',
      title: '恐慌指数',
      description: '波动率的上升往往先于叙事变坏。',
      apiPath: '/api/cn/broad/volatility.json',
      chart: { id: 'cn-broad-volatility', title: '波动率（示例）' },
      relatedKeys: ['drawdown', 'valuation'],
    },
    valuation: {
      key: 'valuation',
      title: '估值锚点',
      description: '均值回归的坐标系：今天到底贵不贵。',
      apiPath: '/api/cn/broad/valuation.json',
      chart: { id: 'cn-broad-valuation', title: '估值带（示例）' },
      howToRead: '估值不是择时神器，而是风险贴水的温度计：高分位意味着未来回报更多依赖盈利兑现。',
      relatedKeys: ['davis-decomposition', 'roe-anchor'],
    },
    'davis-decomposition': {
      key: 'davis-decomposition',
      title: '戴维斯拆解',
      description: '把年度涨跌拆成 EPS 增长与估值扩张。',
      apiPath: '/api/cn/broad/davis-decomposition.json',
      chart: { id: 'cn-broad-davis', title: 'EPS vs PE（示例）' },
      relatedKeys: ['annual', 'valuation'],
    },
    distribution: {
      key: 'distribution',
      title: '收益分布',
      description: '均值背后是肥尾：回报的概率密度。',
      apiPath: '/api/cn/broad/distribution.json',
      chart: { id: 'cn-broad-distribution', title: '年度回报分布（示例）' },
      relatedKeys: ['annual', 'drawdown'],
    },
    'style-ratios': {
      key: 'style-ratios',
      title: '风格比值',
      description: '大盘/小盘、价值/成长的周期往复。',
      apiPath: '/api/cn/broad/style-ratios.json',
      chart: { id: 'cn-broad-style', title: '风格比值（示例）' },
      relatedKeys: ['valuation', 'sector-evolution'],
    },
    seasonality: {
      key: 'seasonality',
      title: '季节性',
      description: '日历效应的统计学验证。',
      apiPath: '/api/cn/broad/seasonality.json',
      chart: { id: 'cn-broad-seasonality', title: '月度季节性（示例）' },
      relatedKeys: ['annual', 'distribution'],
    },
    'sector-evolution': {
      key: 'sector-evolution',
      title: '行业权重迁移',
      description: '指数内部的骨骼：行业权重如何迁移。',
      apiPath: '/api/cn/broad/sector-evolution.json',
      chart: { id: 'cn-broad-sector-evolution', title: '行业权重（示例）' },
      relatedKeys: ['hs300', 'roe-anchor'],
    },
    'roe-anchor': {
      key: 'roe-anchor',
      title: 'ROE 锚点',
      description: '复利的物理重力：盈利能力与资本效率。',
      apiPath: '/api/cn/broad/roe-anchor.json',
      chart: { id: 'cn-broad-roe', title: 'ROE 与回报（示例）' },
      relatedKeys: ['valuation', 'davis-decomposition'],
    },
    breadth: {
      key: 'breadth',
      title: '市场广度',
      description: '上涨并非总是“全市场一起涨”：广度决定行情质量。',
      lead: '当指数上涨但广度走弱，往往意味着上涨由少数权重驱动；当广度扩散，行情更可能“可持续”。',
      judgement: '优先把广度当作“扩散/收敛”的指标：扩散意味着风险偏好扩张，收敛意味着集中度上升与脆弱性上升。',
      apiPath: '/api/cn/broad/breadth.json',
      chart: { id: 'cn-broad-breadth', title: '市场广度（示例）' },
      howToRead: '看两件事：指数趋势与广度趋势是否同向；以及广度的拐点是否领先于指数的拐点。',
      keyFindings: ['广度走弱的上涨更依赖少数权重，回撤往往更“同步”。', '广度扩散通常对应更广泛的风险偏好改善，轮动空间也更大。'],
      methodology: '当前为示例数据；真实版本可用“上涨家数占比/新高新低差/等权指数相对强弱”等指标之一，并固定计算口径。',
      sources: ['示例数据：静态 JSON（后续可替换为公开市场广度指标）。'],
      relatedKeys: ['concentration', 'sector-evolution', 'style-ratios'],
    },
    concentration: {
      key: 'concentration',
      title: '集中度',
      description: '当 Top 权重变得更重，指数更像“少数股票的加权投票”。',
      lead: '集中度上升会改变风险形态：上涨更依赖龙头，回撤也更容易被龙头同步放大。',
      judgement: '集中度不是“好/坏”，而是“暴露变化”：当集中度走高，分散化的边际效果下降，风险更集中在少数叙事上。',
      apiPath: '/api/cn/broad/concentration.json',
      chart: { id: 'cn-broad-concentration', title: 'Top10 权重占比（示例）' },
      howToRead: '关注集中度趋势与市场风格：当集中度走高但广度走弱，往往对应“抱团/龙头行情”。',
      keyFindings: ['集中度上升会让指数对少数权重更敏感，解释了“指数不跌但个股很难”的体感。'],
      methodology: '当前为示例数据；真实版本可按指数成分权重计算 TopN 权重占比，并按固定频率更新。',
      sources: ['示例数据：静态 JSON（后续可替换为公开指数成分权重数据）。'],
      relatedKeys: ['breadth', 'sector-evolution'],
    },
    eras: {
      key: 'eras',
      title: '六时代',
      description: '用断代把噪声压扁：制度与结构的变迁。',
      apiPath: '/api/cn/broad/eras.json',
      chart: { id: 'cn-broad-eras', title: '时代切片（示例）' },
      relatedKeys: ['shanghai-composite', 'drawdown'],
    },
  },
  related: [
    { href: '/cn/sectors', title: '行业（Sectors）', description: '把指数拆成行业轮动与估值对比。' },
    { href: '/cn/clusters', title: '抱团（Clusters）', description: '把“集中度”变成一张可读的谱系图。' },
  ],
};

