import type { HubDef } from '../types';

export const cnBroadHub: HubDef = {
  market: 'cn',
  module: 'broad',
  slug: '/cn/broad',
  lang: 'zh-CN',
  title: '宽基与时代 | A股编年史',
  description: '以核心宽基指数为锚，观察长期回报形状、年度波动、回撤与估值钟摆。',
  heroTitle: 'The Market / 宽基',
  heroDescription: '把一条指数拉到足够长，答案会从“涨跌”变成“形状”：回报、回撤、估值与结构一起决定这段复利曲线。',
  sections: [
    {
      sectionNumber: '1',
      title: '核心指数',
      panelKeys: ['shanghai-composite', 'shenzhen-component', 'hs300', 'chinext', 'star50', 'csi500'],
    },
    {
      sectionNumber: '2',
      title: '周期与风险',
      panelKeys: ['annual', 'drawdown', 'intrayear-turbulence', 'volatility'],
    },
    {
      sectionNumber: '3',
      title: '估值与拆解',
      panelKeys: ['valuation', 'davis-decomposition', 'distribution', 'style-ratios', 'seasonality'],
    },
    {
      sectionNumber: '4',
      title: '结构与效率',
      panelKeys: ['sector-evolution', 'roe-anchor', 'eras'],
    },
  ],
  panels: {
    'shanghai-composite': {
      key: 'shanghai-composite',
      title: '上证综指（000001）',
      description: '最“老”的那条曲线：从 1990 年起的市场总览。',
      lead: '上证综指并不“代表中国最好公司”，但它记录了资本市场从无到有的全部噪声与全部周期。',
      apiPath: '/api/cn/broad/shanghai-composite.json',
      chart: { id: 'cn-broad-shanghai-composite', title: '上证综指长期价格（示例）' },
      howToRead: '把它当作“市场体温计”而不是投资组合：关注长期区间的回撤深度与修复耗时，而非单点高低。',
      sources: ['示例数据：脚本随机生成；后续将替换为公开行情与指数历史数据。'],
      relatedKeys: ['hs300', 'drawdown', 'eras'],
    },
    'shenzhen-component': {
      key: 'shenzhen-component',
      title: '深证成指（399001）',
      description: '更偏成长与中小盘的一面镜子。',
      apiPath: '/api/cn/broad/shenzhen-component.json',
      chart: { id: 'cn-broad-shenzhen-component', title: '深证成指长期价格（示例）' },
      relatedKeys: ['chinext', 'hs300'],
    },
    hs300: {
      key: 'hs300',
      title: '沪深300（000300）',
      description: '机构化时代的核心资产篮子。',
      apiPath: '/api/cn/broad/hs300.json',
      chart: { id: 'cn-broad-hs300', title: '沪深300长期价格（示例）' },
      relatedKeys: ['valuation', 'sector-evolution', 'roe-anchor'],
    },
    chinext: {
      key: 'chinext',
      title: '创业板指（399006）',
      description: '成长股的高波动样本。',
      apiPath: '/api/cn/broad/chinext.json',
      chart: { id: 'cn-broad-chinext', title: '创业板指长期价格（示例）' },
      relatedKeys: ['distribution', 'drawdown'],
    },
    star50: {
      key: 'star50',
      title: '科创50（000688）',
      description: '硬科技定价与风险偏好变化的窗口。',
      apiPath: '/api/cn/broad/star50.json',
      chart: { id: 'cn-broad-star50', title: '科创50长期价格（示例）' },
      relatedKeys: ['valuation', 'drawdown'],
    },
    csi500: {
      key: 'csi500',
      title: '中证500（000905）',
      description: '中盘弹性的代表。',
      apiPath: '/api/cn/broad/csi500.json',
      chart: { id: 'cn-broad-csi500', title: '中证500长期价格（示例）' },
      relatedKeys: ['style-ratios', 'distribution'],
    },
    annual: {
      key: 'annual',
      title: '年度回报',
      description: '把“长期复利”拆回每一年的结账。',
      apiPath: '/api/cn/broad/annual.json',
      chart: { id: 'cn-broad-annual', title: '年度回报（示例）' },
      howToRead: '正负柱体之外，更重要的是：盈利年/亏损年的频率、极端年份的肥尾，以及它们如何塑造风险承受能力。',
      relatedKeys: ['distribution', 'drawdown'],
    },
    drawdown: {
      key: 'drawdown',
      title: '回撤名册',
      description: '市场给恐惧开出的价格：深度与修复。',
      apiPath: '/api/cn/broad/drawdown.json',
      chart: { id: 'cn-broad-drawdown', title: '历史回撤（示例）' },
      relatedKeys: ['annual', 'intrayear-turbulence'],
    },
    'intrayear-turbulence': {
      key: 'intrayear-turbulence',
      title: '年内波动',
      description: '同一年里，最大回撤与最终收益的反差。',
      apiPath: '/api/cn/broad/intrayear-turbulence.json',
      chart: { id: 'cn-broad-intrayear', title: '年内最大回撤 vs 年终收益（示例）' },
      relatedKeys: ['drawdown', 'annual'],
    },
    volatility: {
      key: 'volatility',
      title: '恐慌指数',
      description: '波动率的上升往往先于叙事变坏。',
      apiPath: '/api/cn/broad/volatility.json',
      chart: { id: 'cn-broad-volatility', title: '波动率（示例）' },
      relatedKeys: ['drawdown', 'valuation'],
    },
    valuation: {
      key: 'valuation',
      title: '估值锚点',
      description: '均值回归的坐标系：今天到底贵不贵。',
      apiPath: '/api/cn/broad/valuation.json',
      chart: { id: 'cn-broad-valuation', title: '估值带（示例）' },
      howToRead: '估值不是择时神器，而是风险贴水的温度计：高分位意味着未来回报更多依赖盈利兑现。',
      relatedKeys: ['davis-decomposition', 'roe-anchor'],
    },
    'davis-decomposition': {
      key: 'davis-decomposition',
      title: '戴维斯拆解',
      description: '把年度涨跌拆成 EPS 增长与估值扩张。',
      apiPath: '/api/cn/broad/davis-decomposition.json',
      chart: { id: 'cn-broad-davis', title: 'EPS vs PE（示例）' },
      relatedKeys: ['annual', 'valuation'],
    },
    distribution: {
      key: 'distribution',
      title: '收益分布',
      description: '均值背后是肥尾：回报的概率密度。',
      apiPath: '/api/cn/broad/distribution.json',
      chart: { id: 'cn-broad-distribution', title: '年度回报分布（示例）' },
      relatedKeys: ['annual', 'drawdown'],
    },
    'style-ratios': {
      key: 'style-ratios',
      title: '风格比值',
      description: '大盘/小盘、价值/成长的周期往复。',
      apiPath: '/api/cn/broad/style-ratios.json',
      chart: { id: 'cn-broad-style', title: '风格比值（示例）' },
      relatedKeys: ['valuation', 'sector-evolution'],
    },
    seasonality: {
      key: 'seasonality',
      title: '季节性',
      description: '日历效应的统计学验证。',
      apiPath: '/api/cn/broad/seasonality.json',
      chart: { id: 'cn-broad-seasonality', title: '月度季节性（示例）' },
      relatedKeys: ['annual', 'distribution'],
    },
    'sector-evolution': {
      key: 'sector-evolution',
      title: '行业权重迁移',
      description: '指数内部的骨骼：行业权重如何迁移。',
      apiPath: '/api/cn/broad/sector-evolution.json',
      chart: { id: 'cn-broad-sector-evolution', title: '行业权重（示例）' },
      relatedKeys: ['hs300', 'roe-anchor'],
    },
    'roe-anchor': {
      key: 'roe-anchor',
      title: 'ROE 锚点',
      description: '复利的物理重力：盈利能力与资本效率。',
      apiPath: '/api/cn/broad/roe-anchor.json',
      chart: { id: 'cn-broad-roe', title: 'ROE 与回报（示例）' },
      relatedKeys: ['valuation', 'davis-decomposition'],
    },
    eras: {
      key: 'eras',
      title: '六时代',
      description: '用断代把噪声压扁：制度与结构的变迁。',
      apiPath: '/api/cn/broad/eras.json',
      chart: { id: 'cn-broad-eras', title: '时代切片（示例）' },
      relatedKeys: ['shanghai-composite', 'drawdown'],
    },
  },
  related: [
    { href: '/cn/sectors', title: '行业（Sectors）', description: '把指数拆成行业轮动与估值对比。' },
    { href: '/cn/clusters', title: '抱团（Clusters）', description: '把“集中度”变成一张可读的谱系图。' },
  ],
};

