import type { HubDef } from '../types';

export const cnSectorsHub: HubDef = {
  market: 'cn',
  module: 'sectors',
  slug: '/cn/sectors',
  lang: 'zh-CN',
  title: '行业 | A股编年史',
  description: '把市场拆成行业：轮动、估值、结构与风险暴露。',
  heroTitle: 'Sectors / 行业',
  heroDescription: '行业不是“赛道故事”，而是一组可度量的暴露：估值、盈利、周期与政策敏感性。',
  sections: [
    {
      sectionNumber: '1',
      title: '重点行业',
      panelKeys: ['baijiu', 'pharma', 'new-energy', 'semi', 'banks', 'property', 'ai'],
    },
    {
      sectionNumber: '2',
      title: '总览',
      panelKeys: ['rotation', 'sector-valuation', 'sector-momentum', 'sector-drawdown'],
    },
  ],
  panels: {
    baijiu: {
      key: 'baijiu',
      title: '白酒',
      description: '高 ROE 叙事与估值钟摆的极端样本。',
      lead: '白酒往往被当成“消费信仰”，但更值得研究的是：当高 ROE 被市场过度确信时，估值会如何先扩张、再收缩。',
      judgement: '白酒的主要风险往往不是“增长突然消失”，而是“估值从高确定性叙事中回落”。当相对收益高位横盘，优先警惕估值压缩而非业绩波动。',
      apiPath: '/api/cn/sectors/baijiu.json',
      chart: { id: 'cn-sectors-baijiu', title: '白酒行业（示例）' },
      howToRead: '先把它当成“相对收益曲线”去读：关注相对沪深300的趋势段与回撤段，理解拥挤交易的形成与退潮。',
      keyFindings: [
        '行业的长期超额收益往往来自少数阶段性“估值重估”，而非稳定的线性增长。',
        '当相对收益曲线进入高位横盘时，风险往往转向“估值压缩”而不是“业绩不及预期”。',
      ],
      methodology: '当前为示例数据；真实版本建议使用行业指数相对沪深300的对数相对强弱（或累计超额），并统一复权与频率口径。',
      sources: ['示例数据：脚本随机生成；后续将替换为公开行业指数与成分数据。'],
      relatedLinks: [
        { href: '/cn/broad/valuation', title: '估值锚点（宽基）', description: '把“贵/便宜”放在同一坐标系里读。' },
        { href: '/cn/sectors/sector-valuation', title: '行业估值对比', description: '横截面看分位，而不是看绝对值。' },
      ],
      relatedKeys: ['sector-valuation', 'rotation'],
    },
    pharma: {
      key: 'pharma',
      title: '医药',
      description: '政策、创新与估值的三重变量。',
      lead: '医药的回报经常来自“研发兑现 + 政策扰动 + 估值重估”的共同作用：单看价格很容易误判周期位置。',
      judgement: '医药的关键不是“是否景气”，而是“景气能否穿透到现金流，以及估值是否已提前计价”。当相对收益走强但估值分位同样走高，风险溢价可能在收缩。',
      apiPath: '/api/cn/sectors/pharma.json',
      chart: { id: 'cn-sectors-pharma', title: '医药行业（示例）' },
      howToRead: '把它当成“相对收益曲线”读：趋势段代表风险偏好与盈利预期共同改善；回撤段往往由政策/定价扰动触发，并被估值放大。',
      keyFindings: ['医药的高景气阶段往往伴随更高的估值溢价，回撤更多来自估值压缩而非利润塌陷。', '当行业内部结构分化扩大时，指数层面可能进入“看似横盘、内部轮动剧烈”的阶段。'],
      methodology: '当前为示例数据；真实版本建议使用行业指数相对沪深300的累计超额，并配套估值分位或盈利修正指标作为第二张对照图。',
      sources: ['示例数据：脚本随机生成；后续将替换为公开行业指数与成分数据。'],
      relatedKeys: ['sector-valuation', 'rotation'],
    },
    'new-energy': {
      key: 'new-energy',
      title: '新能源',
      description: '高增速与高波动并存。',
      lead: '新能源的赔率来自“渗透率提升”，风险来自“产能周期与价格战”。高增速并不保证高回报，估值与供需更关键。',
      judgement: '当相对收益走强但回撤也更深，往往意味着市场在为更高的不确定性定价。研究重点是：增速能否转化为可持续的利润率。',
      apiPath: '/api/cn/sectors/new-energy.json',
      chart: { id: 'cn-sectors-new-energy', title: '新能源行业（示例）' },
      howToRead: '优先识别“趋势段/回撤段”：趋势段常由景气与估值共同推动；回撤段常由价格、库存与政策预期的反转触发。',
      keyFindings: ['高波动行业更容易出现“先涨估值、后验业绩”的路径依赖。', '当相对收益曲线进入震荡下行时，往往对应利润率压力与预期下修。'],
      methodology: '当前为示例数据；真实版本建议用行业指数相对沪深300的对数相对强弱，并叠加原材料价格或产品价格作为周期因子。',
      sources: ['示例数据：脚本随机生成；后续将替换为公开行业指数与成分数据。'],
      relatedKeys: ['sector-valuation', 'rotation'],
    },
    semi: {
      key: 'semi',
      title: '半导体',
      description: '周期与国产替代叙事交织的板块。',
      lead: '半导体既是宏观周期的放大器，也是产业政策的受力点。价格里同时包含“景气周期”与“叙事溢价”。',
      judgement: '把半导体当作“高久期 + 高波动”的组合：当相对收益强而估值也高，回撤往往更依赖估值压缩；当估值低位时，反弹更依赖景气改善。',
      apiPath: '/api/cn/sectors/semi.json',
      chart: { id: 'cn-sectors-semi', title: '半导体行业（示例）' },
      howToRead: '识别“加速段”与“去杠杆段”：加速段通常表现为相对收益陡峭上行；去杠杆段往往是长时间回撤与横盘的组合。',
      keyFindings: ['半导体的回撤往往呈“簇状出现”，多个阶段性下跌会叠加成深回撤。', '指数层面上行容易被龙头权重主导，结构分化可能在指数里被掩盖。'],
      methodology: '当前为示例数据；真实版本建议用行业指数相对沪深300，并叠加估值带或盈利修正，区分“景气驱动”与“估值驱动”。',
      sources: ['示例数据：脚本随机生成；后续将替换为公开行业指数与成分数据。'],
      relatedKeys: ['ai', 'sector-valuation'],
    },
    banks: {
      key: 'banks',
      title: '银行',
      description: '分红、利差与风险定价。',
      lead: '银行更像“信用与利率的定价器”，而不是传统意义上的成长行业：分红、拨备与资产质量决定长期回报形状。',
      judgement: '银行的核心矛盾常在“分红确定性”与“信用不确定性”之间切换：当相对收益走强但估值仍低位，市场可能在上调风险溢价而非追逐成长。',
      apiPath: '/api/cn/sectors/banks.json',
      chart: { id: 'cn-sectors-banks', title: '银行行业（示例）' },
      howToRead: '先用相对收益判断市场对风险溢价的定价方向，再用估值分位判断“反弹空间”与“折价理由”是否在变化。',
      keyFindings: ['低估值并不等于低风险：折价往往对应资产质量与周期敏感性。', '当银行相对收益走强，常对应利率预期、风险偏好或分红叙事的重估。'],
      methodology: '当前为示例数据；真实版本建议引入 PB/股息率分位与利率曲线作为对照，解释相对收益拐点。',
      sources: ['示例数据：脚本随机生成；后续将替换为公开行业指数与成分数据。'],
      relatedKeys: ['property', 'sector-valuation'],
    },
    property: {
      key: 'property',
      title: '地产',
      description: '信用周期的放大镜。',
      lead: '地产更多反映信用扩张/收缩，而不是单纯的“销售好坏”。当信用收缩，回撤会以更陡峭、更持续的形式出现。',
      judgement: '地产的研究重点是“信用条件是否边际改善”：相对收益的反弹如果缺少信用验证，往往难以持续。',
      apiPath: '/api/cn/sectors/property.json',
      chart: { id: 'cn-sectors-property', title: '地产行业（示例）' },
      howToRead: '把它当成“信用温度计”：快速上行常对应信用扩张预期；长时间下行常对应融资约束与资产负债表修复。',
      keyFindings: ['地产回撤通常具有“路径依赖”，一旦进入长期下行，反弹往往更依赖政策与信用而非盈利。'],
      methodology: '当前为示例数据；真实版本建议叠加信用利差、融资环境与政策事件作为注释层。',
      sources: ['示例数据：脚本随机生成；后续将替换为公开行业指数与成分数据。'],
      relatedKeys: ['banks', 'rotation'],
    },
    ai: {
      key: 'ai',
      title: 'AI',
      description: '拥挤度与估值扩张的试金石。',
      lead: 'AI 更像“叙事与久期”的合成：当预期快速抬升，估值扩张会比盈利兑现更先发生。',
      judgement: 'AI 的关键风险是“估值先行、业绩后验”：当相对收益加速但估值分位也在抬升，后续回报更依赖兑现速度。',
      apiPath: '/api/cn/sectors/ai.json',
      chart: { id: 'cn-sectors-ai', title: 'AI 行业（示例）' },
      howToRead: '优先识别“加速段”与“回撤段”：加速段代表叙事扩散与风险偏好扩张；回撤段代表预期再定价。',
      keyFindings: ['主题行业的收益往往集中在少数阶段性加速期，横盘期的交易体验差。', '当主题内部扩散到二三线时，指数可能见到阶段性高点。'],
      methodology: '当前为示例数据；真实版本建议引入成交额占比/换手率等拥挤度代理，区分“上涨的质量”。',
      sources: ['示例数据：脚本随机生成；后续将替换为公开行业指数与成分数据。'],
      relatedKeys: ['semi', 'rotation'],
    },
    rotation: {
      key: 'rotation',
      title: '行业轮动总图',
      description: '用同一坐标系看轮动，而不是逐个叙事。',
      lead: '轮动不是“故事接力”，而是风险溢价在行业之间迁移的结果。把行业放在同一张图上，才能看见“谁在吸收波动”。',
      judgement: '先看“线条是否分叉”，再看“领先是否持续”：分叉意味着结构性行情，纠缠意味着存量博弈；持续领先往往比短期拉升更重要。',
      apiPath: '/api/cn/sectors/rotation.json',
      chart: { id: 'cn-sectors-rotation', title: '行业轮动（示例）' },
      howToRead: '把每条线理解为“相对强弱”：当多数行业同步上行时，市场处于风险偏好扩张；当少数行业独立走强时，往往是防御或结构性行情。',
      keyFindings: [
        '真正的轮动通常发生在相对强弱的拐点，而不是绝对价格的新高/新低。',
        '若轮动图呈现“线条纠缠”而非清晰领涨，常对应存量博弈与主题快速切换。',
      ],
      methodology: '当前为示例数据；真实版本可用各行业指数相对沪深300的累计超额构造，并统一起点=100 的基准化方式，避免绝对点位不可比。',
      sources: ['示例数据：脚本随机生成；后续将替换为行业指数相对收益与回撤数据。'],
      relatedLinks: [{ href: '/cn/broad/style-ratios', title: '风格比值（宽基）', description: '轮动的另一种表达：大盘/小盘与风格周期。' }],
      relatedKeys: ['sector-valuation'],
    },
    'sector-valuation': {
      key: 'sector-valuation',
      title: '行业估值对比',
      description: '横截面：谁在高估/低估区间。',
      lead: '估值对比的意义不在“挑最便宜”，而在为风险暴露定价：高分位更依赖盈利兑现，低分位更依赖均值回归与分红。',
      judgement: '优先把估值当作“风险温度计”：高分位意味着回报更依赖兑现，低分位意味着折价需要被解释。',
      apiPath: '/api/cn/sectors/sector-valuation.json',
      chart: { id: 'cn-sectors-valuation', title: '行业估值（示例）' },
      howToRead: '优先比较“分位”而不是绝对数值：不同行业的商业模式与会计结构不同，绝对 PE/PB 的可比性有限。',
      keyFindings: [
        '高估值行业的回撤往往由估值压缩主导，盈利下修是第二阶段。',
        '低估值行业的关键不是“便宜”，而是“为什么长期便宜”：ROE、资产质量与周期敏感性往往解释了折价。',
      ],
      methodology: '当前为示例数据；真实版本建议以“行业估值历史分位”（PE/PB/股息率等）为主，并在同一行业内用一致口径计算分位，避免跨行业绝对值误导。',
      sources: ['示例数据：脚本随机生成；后续将替换为行业估值（PE/PB/分位数）时间序列。'],
      relatedLinks: [{ href: '/cn/broad/valuation', title: '估值锚点（宽基）', description: '把行业估值放回市场的估值坐标系。' }],
      relatedKeys: ['rotation'],
    },
    'sector-momentum': {
      key: 'sector-momentum',
      title: '行业动量（12M）',
      description: '横截面：谁在走强，谁在掉队。',
      lead: '动量不是“追涨杀跌”的口号，而是市场在用价格投票：哪些行业正在吸收资金与风险偏好。',
      judgement: '动量更适合用来识别“结构性强势”而不是预测“下一周谁更强”：优先看领先是否持续，以及领先行业是否集中在同一风格上。',
      apiPath: '/api/cn/sectors/sector-momentum.json',
      chart: { id: 'cn-sectors-sector-momentum', title: '行业动量（示例）' },
      howToRead: '把它当作“横截面排名”：领先行业越集中，结构性行情越强；领先越分散，市场可能处于扩散上涨或快速轮动。',
      keyFindings: ['动量图能补全轮动图的“当下快照”：轮动讲路径，动量讲当前领先。'],
      methodology: '当前为示例数据；真实版本可按行业指数近 252 交易日收益或相对沪深300超额收益计算，并固定窗口与复权口径。',
      sources: ['示例数据：静态 JSON（后续可替换为公开行业指数收益数据）。'],
      relatedKeys: ['rotation', 'sector-valuation'],
    },
    'sector-drawdown': {
      key: 'sector-drawdown',
      title: '行业回撤（近一年）',
      description: '横截面：风险侧的比较。',
      lead: '回撤是风险暴露的“最坏时刻”刻度：它比波动率更直观，也更接近真实持有体验。',
      judgement: '把回撤与动量一起读：高动量+高回撤通常意味着高波动风格；低动量+低回撤更偏防御或低β。',
      apiPath: '/api/cn/sectors/sector-drawdown.json',
      chart: { id: 'cn-sectors-sector-drawdown', title: '行业回撤（示例）' },
      howToRead: '关注回撤的“相对位置”而不是绝对值：当多数行业回撤同步扩大，市场处于风险溢价扩张；当回撤分化，结构性行情更明显。',
      keyFindings: ['回撤横截面能解释“同样的上涨预期，为什么不同赛道的持有体验差异极大”。'],
      methodology: '当前为示例数据；真实版本可按行业指数近一年滚动最大回撤计算，并固定窗口（如 252 交易日）。',
      sources: ['示例数据：静态 JSON（后续可替换为公开行业指数历史数据）。'],
      relatedKeys: ['rotation', 'sector-momentum'],
    },
  },
  related: [
    { href: '/cn/broad', title: '宽基（Broad）', description: '先把市场的“母曲线”看清。' },
    { href: '/cn/clusters', title: '抱团（Clusters）', description: '从集中度与相关性理解拥挤交易。' },
  ],
};

