import type { HubDef } from '../types';

export const cnSectorsHub: HubDef = {
  market: 'cn',
  module: 'sectors',
  slug: '/cn/sectors',
  lang: 'zh-CN',
  title: '行业 | A股编年史',
  description: '把市场拆成行业：轮动、估值、结构与风险暴露。',
  heroTitle: 'Sectors / 行业',
  heroDescription: '行业不是“赛道故事”，而是一组可度量的暴露：估值、盈利、周期与政策敏感性。',
  sections: [
    {
      sectionNumber: '1',
      title: '重点行业',
      panelKeys: ['baijiu', 'pharma', 'new-energy', 'semi', 'banks', 'property', 'ai'],
    },
    {
      sectionNumber: '2',
      title: '总览',
      panelKeys: ['rotation', 'sector-valuation'],
    },
  ],
  panels: {
    baijiu: {
      key: 'baijiu',
      title: '白酒',
      description: '高 ROE 叙事与估值钟摆的极端样本。',
      lead: '白酒往往被当成“消费信仰”，但更值得研究的是：当高 ROE 被市场过度确信时，估值会如何先扩张、再收缩。',
      apiPath: '/api/cn/sectors/baijiu.json',
      chart: { id: 'cn-sectors-baijiu', title: '白酒行业（示例）' },
      howToRead: '先把它当成“相对收益曲线”去读：关注相对沪深300的趋势段与回撤段，理解拥挤交易的形成与退潮。',
      keyFindings: [
        '行业的长期超额收益往往来自少数阶段性“估值重估”，而非稳定的线性增长。',
        '当相对收益曲线进入高位横盘时，风险往往转向“估值压缩”而不是“业绩不及预期”。',
      ],
      sources: ['示例数据：脚本随机生成；后续将替换为公开行业指数与成分数据。'],
      relatedKeys: ['sector-valuation', 'rotation'],
    },
    pharma: {
      key: 'pharma',
      title: '医药',
      description: '政策、创新与估值的三重变量。',
      apiPath: '/api/cn/sectors/pharma.json',
      chart: { id: 'cn-sectors-pharma', title: '医药行业（示例）' },
      relatedKeys: ['sector-valuation', 'rotation'],
    },
    'new-energy': {
      key: 'new-energy',
      title: '新能源',
      description: '高增速与高波动并存。',
      apiPath: '/api/cn/sectors/new-energy.json',
      chart: { id: 'cn-sectors-new-energy', title: '新能源行业（示例）' },
      relatedKeys: ['sector-valuation', 'rotation'],
    },
    semi: {
      key: 'semi',
      title: '半导体',
      description: '周期与国产替代叙事交织的板块。',
      apiPath: '/api/cn/sectors/semi.json',
      chart: { id: 'cn-sectors-semi', title: '半导体行业（示例）' },
      relatedKeys: ['ai', 'sector-valuation'],
    },
    banks: {
      key: 'banks',
      title: '银行',
      description: '分红、利差与风险定价。',
      apiPath: '/api/cn/sectors/banks.json',
      chart: { id: 'cn-sectors-banks', title: '银行行业（示例）' },
      relatedKeys: ['property', 'sector-valuation'],
    },
    property: {
      key: 'property',
      title: '地产',
      description: '信用周期的放大镜。',
      apiPath: '/api/cn/sectors/property.json',
      chart: { id: 'cn-sectors-property', title: '地产行业（示例）' },
      relatedKeys: ['banks', 'rotation'],
    },
    ai: {
      key: 'ai',
      title: 'AI',
      description: '拥挤度与估值扩张的试金石。',
      apiPath: '/api/cn/sectors/ai.json',
      chart: { id: 'cn-sectors-ai', title: 'AI 行业（示例）' },
      relatedKeys: ['semi', 'rotation'],
    },
    rotation: {
      key: 'rotation',
      title: '行业轮动总图',
      description: '用同一坐标系看轮动，而不是逐个叙事。',
      lead: '轮动不是“故事接力”，而是风险溢价在行业之间迁移的结果。把行业放在同一张图上，才能看见“谁在吸收波动”。',
      apiPath: '/api/cn/sectors/rotation.json',
      chart: { id: 'cn-sectors-rotation', title: '行业轮动（示例）' },
      howToRead: '把每条线理解为“相对强弱”：当多数行业同步上行时，市场处于风险偏好扩张；当少数行业独立走强时，往往是防御或结构性行情。',
      keyFindings: [
        '真正的轮动通常发生在相对强弱的拐点，而不是绝对价格的新高/新低。',
        '若轮动图呈现“线条纠缠”而非清晰领涨，常对应存量博弈与主题快速切换。',
      ],
      sources: ['示例数据：脚本随机生成；后续将替换为行业指数相对收益与回撤数据。'],
      relatedKeys: ['sector-valuation'],
    },
    'sector-valuation': {
      key: 'sector-valuation',
      title: '行业估值对比',
      description: '横截面：谁在高估/低估区间。',
      lead: '估值对比的意义不在“挑最便宜”，而在为风险暴露定价：高分位更依赖盈利兑现，低分位更依赖均值回归与分红。',
      apiPath: '/api/cn/sectors/sector-valuation.json',
      chart: { id: 'cn-sectors-valuation', title: '行业估值（示例）' },
      howToRead: '优先比较“分位”而不是绝对数值：不同行业的商业模式与会计结构不同，绝对 PE/PB 的可比性有限。',
      keyFindings: [
        '高估值行业的回撤往往由估值压缩主导，盈利下修是第二阶段。',
        '低估值行业的关键不是“便宜”，而是“为什么长期便宜”：ROE、资产质量与周期敏感性往往解释了折价。',
      ],
      sources: ['示例数据：脚本随机生成；后续将替换为行业估值（PE/PB/分位数）时间序列。'],
      relatedKeys: ['rotation'],
    },
  },
  related: [
    { href: '/cn/broad', title: '宽基（Broad）', description: '先把市场的“母曲线”看清。' },
    { href: '/cn/clusters', title: '抱团（Clusters）', description: '从集中度与相关性理解拥挤交易。' },
  ],
};

