import type { HubDef } from '../types';

export const usNasdaqHub: HubDef = {
  market: 'us',
  module: 'nasdaq',
  slug: '/us/nasdaq',
  lang: 'zh-CN',
  title: '纳斯达克（Nasdaq） | A股编年史',
  description: '科技权重更高的复利曲线：长期形状、年度结果、回撤与估值锚点。',
  heroTitle: 'Nasdaq / 纳斯达克',
  heroDescription: '纳指是“久期 × 叙事”的交汇处：泡沫在价格上看起来相似，但在估值与集中度上往往不同。',
  sections: [
    { sectionNumber: '1', title: '长期形状', panelKeys: ['composite'] },
    { sectionNumber: '2', title: '年度与回撤', panelKeys: ['annual-returns', 'drawdowns'] },
    { sectionNumber: '3', title: '估值锚点', panelKeys: ['valuation'] },
  ],
  panels: {
    composite: {
      key: 'composite',
      title: '纳指综合指数（Composite）',
      description: '长期价格曲线（示例数据）。',
      lead: '纳指往往“涨得快、跌得也深”。理解它，重点是把“高速增长”与“高回撤风险”放在同一张图里读。',
      judgement: '把纳指和标普放在同一尺度比较：纳指的优势常来自少数阶段的久期与估值扩张，代价是更深的回撤与更长的修复时间。',
      apiPath: '/api/us/nasdaq/composite.json',
      chart: { id: 'us-nasdaq-composite', title: '纳指综合长期价格（示例）' },
      howToRead: '优先看“趋势段”而不是“单点高低”：当斜率持续变陡，往往意味着盈利预期与估值共同上升；当斜率反转，风险在回撤中兑现。',
      methodology: '示例数据为脚本生成；替换真实数据时建议用周度或月度频率以更清晰地呈现趋势与回撤结构。',
      sources: ['示例数据：scripts/build-us-nasdaq.ts（随机生成）'],
      relatedKeys: ['drawdowns', 'valuation'],
    },
    'annual-returns': {
      key: 'annual-returns',
      title: '年度回报',
      description: '逐年结账（示例数据）。',
      judgement: '年度回报把“高增长指数”的回报路径拆开：更高的上行通常伴随更高的下行尾部。',
      apiPath: '/api/us/nasdaq/annual-returns.json',
      chart: { id: 'us-nasdaq-annual', title: '纳指年度回报（示例）' },
      methodology: '示例数据按区间随机生成年度收益率；替换真实数据后可加上与标普的相对收益对比。',
      sources: ['示例数据：scripts/build-us-nasdaq.ts（随机生成）'],
      relatedKeys: ['composite', 'drawdowns'],
    },
    drawdowns: {
      key: 'drawdowns',
      title: '回撤名册',
      description: '高点到低点的损失（示例数据）。',
      judgement: '纳指的关键风险不是“波动更大”，而是“回撤更深、修复更久”的阶段性出现。',
      apiPath: '/api/us/nasdaq/drawdowns.json',
      chart: { id: 'us-nasdaq-drawdowns', title: '纳指历史回撤（示例）' },
      methodology: '回撤按“距离历史峰值的百分比”计算；真实数据需明确是否包含分红再投资口径。',
      sources: ['示例数据：scripts/build-us-nasdaq.ts（随机生成）'],
      relatedKeys: ['composite', 'valuation'],
    },
    valuation: {
      key: 'valuation',
      title: '估值锚点',
      description: '估值带（示例数据）。',
      judgement: '对高久期资产，估值位置往往比短期业绩更能解释阶段性回撤。',
      apiPath: '/api/us/nasdaq/valuation.json',
      chart: { id: 'us-nasdaq-valuation', title: '纳指估值带（示例）' },
      howToRead: '优先看估值带的“偏离程度”与“回归速度”，再结合回撤名册判断风险溢价的变化。',
      methodology: '当前为示例估值带结构；替换真实估值时需明确口径与样本窗口。',
      sources: ['示例数据：scripts/build-us-nasdaq.ts（随机生成）'],
      relatedKeys: ['annual-returns'],
    },
  },
  related: [
    { href: '/us/sp500', title: '标普500（S&P 500）', description: '作为更宽的基准对照。' },
    { href: '/us/semi', title: '半导体（Semis）', description: '周期叠加与泡沫回声。' },
  ],
};

