import type { HubDef } from '../types';

export const usSp500Hub: HubDef = {
  market: 'us',
  module: 'sp500',
  slug: '/us/sp500',
  lang: 'en',
  title: 'S&P 500 | U.S. Market Chronicle',
  description: 'A century-scale lens on U.S. equities: long-run shape, annual outcomes, drawdowns, and valuation anchors.',
  heroTitle: 'S&P 500',
  heroDescription: 'At a century scale, the market looks like a compounding log curve interrupted by a catalog of drawdowns. This section puts return, valuation, and risk on the same page.',
  sections: [
    { sectionNumber: '1', title: 'Long Run', panelKeys: ['century'] },
    { sectionNumber: '2', title: 'Outcomes', panelKeys: ['annual-returns', 'drawdowns'] },
    { sectionNumber: '3', title: 'Valuation', panelKeys: ['valuation'] },
  ],
  panels: {
    century: {
      key: 'century',
      title: 'Century-Scale Price',
      description: 'The compounding shape over decades (sample data).',
      apiPath: '/api/us/sp500/century.json',
      chart: { id: 'us-sp500-century', title: 'S&P 500 long-run price (sample)' },
      howToRead: 'Use log scale for shape, and compare major drawdowns by depth and recovery time rather than point-to-point changes.',
      sources: ['Sample data generated by scripts; to be replaced by public index history.'],
      relatedKeys: ['drawdowns', 'valuation'],
    },
    'annual-returns': {
      key: 'annual-returns',
      title: 'Annual Returns',
      description: 'Year-by-year outcomes (sample data).',
      apiPath: '/api/us/sp500/annual-returns.json',
      chart: { id: 'us-sp500-annual', title: 'S&P 500 annual returns (sample)' },
      relatedKeys: ['century', 'drawdowns'],
    },
    drawdowns: {
      key: 'drawdowns',
      title: 'Drawdowns',
      description: 'A catalog of losses from peak to trough (sample data).',
      apiPath: '/api/us/sp500/drawdowns.json',
      chart: { id: 'us-sp500-drawdowns', title: 'S&P 500 drawdowns (sample)' },
      relatedKeys: ['century', 'valuation'],
    },
    valuation: {
      key: 'valuation',
      title: 'Valuation Anchor',
      description: 'A temperature gauge for expected returns (sample data).',
      apiPath: '/api/us/sp500/valuation.json',
      chart: { id: 'us-sp500-valuation', title: 'S&P 500 valuation bands (sample)' },
      relatedKeys: ['annual-returns', 'century'],
    },
  },
  related: [
    { href: '/us/nasdaq', title: 'Nasdaq', description: 'Tech-heavy outcomes and bubble comparisons.' },
    { href: '/us/mag7', title: 'Mag7', description: 'Concentration, contribution, and crowding.' },
  ],
};

