import type { HubDef } from '../types';

export const usSp500Hub: HubDef = {
  market: 'us',
  module: 'sp500',
  slug: '/us/sp500',
  lang: 'zh-CN',
  title: '标普500（S&P 500） | A股编年史',
  description: '用世纪尺度观察美股：长期形状、年度结果、回撤名册与估值锚点。',
  heroTitle: 'S&P 500 / 标普500',
  heroDescription: '把尺度拉到足够长，市场更像一条复利曲线，中间夹杂一份回撤名册。本专题把回报、估值与风险放在同一页。',
  sections: [
    { sectionNumber: '1', title: '长期形状', panelKeys: ['century', 'total-return'] },
    { sectionNumber: '2', title: '年度与回撤', panelKeys: ['annual-returns', 'drawdowns'] },
    { sectionNumber: '3', title: '估值与盈利', panelKeys: ['valuation', 'eps'] },
  ],
  panels: {
    century: {
      key: 'century',
      title: '世纪尺度价格',
      description: '跨越数十年的复利形状（示例数据）。',
      lead: '这张图解决的不是“哪一年涨得多”，而是“长期复利的形状是什么，以及大回撤在形状上留下了什么疤痕”。',
      judgement: '用对数尺度读长期形状；用回撤深度与修复时间读风险，而不是用点位高低读结论。',
      apiPath: '/api/us/sp500/century.json',
      chart: { id: 'us-sp500-century', title: '标普500长期价格（示例）' },
      howToRead: '先看形状再看波动：对数坐标更适合比较不同时期的增速；把每次大回撤当作一段“损失-修复”的区间来比较。',
      keyFindings: ['长期曲线的“斜率变化”比短期涨跌更重要：它通常对应盈利与估值的共同变化。', '真正影响长期体验的不是波动本身，而是回撤深度与修复时间。'],
      methodology: '示例数据为脚本随机生成的时间序列；后续可替换为公开指数历史数据，并在生成脚本中固定频率与口径。',
      sources: ['示例数据：scripts/build-us-sp500.ts（随机生成）'],
      relatedKeys: ['drawdowns', 'valuation'],
    },
    'annual-returns': {
      key: 'annual-returns',
      title: '年度回报',
      description: '把长期拆回每一年的结账（示例数据）。',
      lead: '年度回报图能快速告诉你：长期平均值是由“多数普通年份”贡献的，还是由“少数极端年份”决定的。',
      judgement: '看年度回报不是为了预测下一年，而是为了校准对“坏年份”“肥尾”“连续下跌”的心理预期。',
      apiPath: '/api/us/sp500/annual-returns.json',
      chart: { id: 'us-sp500-annual', title: '标普500年度回报（示例）' },
      howToRead: '优先看三件事：亏损年的频率、极端年份的幅度、以及连续几年低迷/高涨的簇状出现。',
      methodology: '示例数据按固定范围随机生成年度收益率；替换真实数据后可叠加通胀调整或股息再投资口径。',
      sources: ['示例数据：scripts/build-us-sp500.ts（随机生成）'],
      relatedKeys: ['century', 'drawdowns'],
    },
    drawdowns: {
      key: 'drawdowns',
      title: '回撤名册',
      description: '从高点到低点的损失目录（示例数据）。',
      lead: '回撤是风险的“计价方式”：它把恐惧从情绪变成了百分比与时间。',
      judgement: '同样的长期回报，不同的回撤深度与修复时间会带来完全不同的持有体验。',
      apiPath: '/api/us/sp500/drawdowns.json',
      chart: { id: 'us-sp500-drawdowns', title: '标普500历史回撤（示例）' },
      howToRead: '把每次跌幅当作区间：最深点（深度）与回到前高所用时间（修复）通常比“哪天见底”更有信息。',
      keyFindings: ['回撤名册能把“长期向上”的叙事，翻译成“你需要忍受什么”。'],
      methodology: '回撤按“距离历史峰值的百分比”计算；替换真实数据时需明确复权口径与频率（周/月）。',
      sources: ['示例数据：scripts/build-us-sp500.ts（随机生成）'],
      relatedKeys: ['century', 'valuation'],
    },
    valuation: {
      key: 'valuation',
      title: '估值锚点',
      description: '为预期回报提供温度计（示例数据）。',
      lead: '估值不是择时神器，但它能回答“未来回报更依赖盈利兑现还是均值回归”。',
      judgement: '当估值处在高分位，未来回报对“盈利兑现”的依赖更高；当估值低分位，均值回归与分红的权重更大。',
      apiPath: '/api/us/sp500/valuation.json',
      chart: { id: 'us-sp500-valuation', title: '标普500估值带（示例）' },
      howToRead: '优先看“分位/偏离均值”的相对位置，而不是绝对 PE 数值；再结合回撤名册判断风险溢价是否在扩张。',
      methodology: '当前为示例估值带（均值与±1σ）结构；替换真实数据时需要明确估值口径（PE TTM / CAPE 等）与样本窗口。',
      sources: ['示例数据：scripts/build-us-sp500.ts（随机生成）'],
      relatedKeys: ['annual-returns', 'century'],
    },
    'total-return': {
      key: 'total-return',
      title: '总回报指数',
      description: '把分红再投入算进去，才是“复利的真实形状”。',
      lead: '价格曲线回答“指数点位怎么走”，总回报曲线回答“如果把股息不断再投入，复利长什么样”。',
      judgement: '长期研究优先看总回报：它把分红这条“隐形现金流”显性化，会改变对长期回报的直觉。',
      apiPath: '/api/us/sp500/total-return.json',
      chart: { id: 'us-sp500-total-return', title: '标普500总回报指数（含分红再投入）' },
      howToRead: '与价格曲线对照：两者差距随时间拉大，代表股息与再投资在复利中累积的贡献。',
      methodology: '总回报指数用月度价格与分红推算：TR_t = TR_{t-1} × (P_t + D_t) / P_{t-1}。',
      sources: ['Shiller 数据：价格(P)、分红(D)、盈利(E)月度序列（脚本抓取并计算）。'],
      relatedKeys: ['century', 'annual-returns', 'drawdowns'],
    },
    eps: {
      key: 'eps',
      title: '每股收益（E）',
      description: '分子端：盈利的长期形状。',
      lead: '估值的分母端决定“能支撑多高的价格”。长期回报最终会回到盈利增长这条主线上。',
      judgement: '当价格远快于盈利上行时，更多是估值扩张；当盈利上行而价格跟不上，更多是估值压缩或风险溢价抬升。',
      apiPath: '/api/us/sp500/eps.json',
      chart: { id: 'us-sp500-eps', title: '标普500盈利（E）' },
      howToRead: '把它与估值带对照：盈利抬升但估值下行，代表“盈利弥补估值”；估值抬升但盈利跟不上，风险更多来自估值回归。',
      methodology: '使用 Shiller 月度 E 序列（名义）。如需 TTM/实值口径，需要进一步处理通胀与窗口平滑。',
      sources: ['Shiller 数据：价格(P)、分红(D)、盈利(E)月度序列（脚本抓取）。'],
      relatedKeys: ['valuation', 'century'],
    },
  },
  related: [
    { href: '/us/nasdaq', title: '纳斯达克（Nasdaq）', description: '科技权重更高：泡沫回声、集中度与估值。' },
    { href: '/us/mag7', title: 'Mag7（七巨头）', description: '集中度、贡献度与拥挤度代理。' },
  ],
};

